# Generated by Django 3.2.6 on 2021-08-15 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=50)),
                ('clinic_address', models.CharField(max_length=150)),
                ('clinic_hphone', models.PositiveSmallIntegerField()),
                ('clinic_cphone', models.PositiveSmallIntegerField()),
                ('clinic_email', models.EmailField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=50)),
                ('vaccine_date', models.DateField()),
                ('vaccine_next_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('cedula', models.IntegerField(null=True)),
                ('direccion', models.CharField(max_length=150)),
                ('hphone', models.IntegerField()),
                ('cphone', models.IntegerField()),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='pet_safe_app.rol')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='pet_safe_app.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_age', models.PositiveSmallIntegerField()),
                ('pet_birth_date', models.DateField()),
                ('pet_breed', models.CharField(max_length=50)),
                ('pet_gender', models.CharField(max_length=6)),
                ('pet_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pet_color', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('is_lost', models.SmallIntegerField()),
                ('pet_image', models.ImageField(upload_to='pet_image/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('pet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_owner', to='pet_safe_app.user')),
                ('pet_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pet_safe_app.pettype')),
                ('vaccines', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_vaccines', to='pet_safe_app.vaccine')),
            ],
        ),
    ]
