# Generated by Django 3.2.6 on 2021-08-08 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=50)),
                ('clinic_address', models.CharField(max_length=150)),
                ('clinic_hphone', models.PositiveSmallIntegerField()),
                ('clinic_cphone', models.PositiveSmallIntegerField()),
                ('clinic_email', models.EmailField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('cedula', models.IntegerField(null=True)),
                ('direccion', models.CharField(max_length=150)),
                ('hphone', models.IntegerField()),
                ('cphone', models.IntegerField()),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='pet_safe_app.rol')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='pet_safe_app.gender')),
            ],
        ),
        migrations.CreateModel(
            name='vetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_age', models.PositiveSmallIntegerField()),
                ('pet_birth_date', models.DateField()),
                ('pet_breed', models.CharField(max_length=50)),
                ('pet_gender', models.CharField(max_length=6)),
                ('pet_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pet_color', models.CharField(max_length=50)),
                ('allergies', models.CharField(max_length=50)),
                ('existing_conditions', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('diagnosis', models.CharField(max_length=250)),
                ('pet_image', models.ImageField(upload_to='pet_image/')),
                ('review_data', models.DateField()),
                ('test_performed', models.CharField(max_length=50)),
                ('test_results', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=250)),
                ('medication', models.CharField(max_length=250)),
                ('comments', models.CharField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('pet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_owner', to='pet_safe_app.user')),
                ('rol', models.ManyToManyField(related_name='veterinarians', to='pet_safe_app.Rol')),
            ],
        ),
        migrations.CreateModel(
            name='ImmunizationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('vaccine', models.CharField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('clinic_vaccine_hist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_vaccines', to='pet_safe_app.clinic')),
                ('pet_vaccine_hist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_vaccines', to='pet_safe_app.vetrecord')),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='rol',
            field=models.ManyToManyField(related_name='clinic_vets', to='pet_safe_app.Rol'),
        ),
    ]
