# Generated by Django 3.2.6 on 2021-08-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_safe_app', '0002_auto_20210808_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_lost',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
