# Generated by Django 3.2.6 on 2021-08-12 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_safe_app', '0003_pet_is_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='vaccines',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_vaccines', to='pet_safe_app.vaccine'),
        ),
    ]
