# Generated by Django 3.2.6 on 2021-08-15 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_safe_app', '0003_auto_20210814_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='vaccines',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='pet_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_vaccines', to='pet_safe_app.pet'),
        ),
    ]
