# Generated by Django 3.2.6 on 2021-08-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_safe_app', '0005_alter_pet_pet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_image',
            field=models.ImageField(blank=True, upload_to='pet_image/'),
        ),
    ]
