# Generated by Django 3.2.6 on 2021-08-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_safe_app', '0010_alter_pet_pet_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
