# Generated by Django 3.2.6 on 2021-08-15 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_safe_app', '0011_alter_pet_pet_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='slug',
        ),
    ]
